# Generated by Django 3.0.2 on 2020-01-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
