# Generated by Django 3.0.2 on 2020-01-31 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jeu', '0002_departement_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='departement',
            name='sous_pref_four',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='departement',
            name='sous_pref_three',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='departement',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jeu.Region'),
        ),
    ]
